version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    command: server /data
    restart: always
    
volumes:
  mongo_data:
  minio_data: